/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSystemRouteImport } from './routes/_layout/system'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutServingRouteImport } from './routes/_layout/serving'
import { Route as LayoutSecopsRouteImport } from './routes/_layout/secops'
import { Route as LayoutModelTrackingRouteImport } from './routes/_layout/model-tracking'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutDashboardSettingsRouteImport } from './routes/_layout/dashboard-settings'
import { Route as LayoutClusterRouteImport } from './routes/_layout/cluster'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemRoute = LayoutSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutServingRoute = LayoutServingRouteImport.update({
  id: '/serving',
  path: '/serving',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSecopsRoute = LayoutSecopsRouteImport.update({
  id: '/secops',
  path: '/secops',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutModelTrackingRoute = LayoutModelTrackingRouteImport.update({
  id: '/model-tracking',
  path: '/model-tracking',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardSettingsRoute = LayoutDashboardSettingsRouteImport.update({
  id: '/dashboard-settings',
  path: '/dashboard-settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClusterRoute = LayoutClusterRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/cluster': typeof LayoutClusterRoute
  '/dashboard-settings': typeof LayoutDashboardSettingsRoute
  '/items': typeof LayoutItemsRoute
  '/model-tracking': typeof LayoutModelTrackingRoute
  '/secops': typeof LayoutSecopsRoute
  '/serving': typeof LayoutServingRoute
  '/settings': typeof LayoutSettingsRoute
  '/system': typeof LayoutSystemRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/cluster': typeof LayoutClusterRoute
  '/dashboard-settings': typeof LayoutDashboardSettingsRoute
  '/items': typeof LayoutItemsRoute
  '/model-tracking': typeof LayoutModelTrackingRoute
  '/secops': typeof LayoutSecopsRoute
  '/serving': typeof LayoutServingRoute
  '/settings': typeof LayoutSettingsRoute
  '/system': typeof LayoutSystemRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/cluster': typeof LayoutClusterRoute
  '/_layout/dashboard-settings': typeof LayoutDashboardSettingsRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/model-tracking': typeof LayoutModelTrackingRoute
  '/_layout/secops': typeof LayoutSecopsRoute
  '/_layout/serving': typeof LayoutServingRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/system': typeof LayoutSystemRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/cluster'
    | '/dashboard-settings'
    | '/items'
    | '/model-tracking'
    | '/secops'
    | '/serving'
    | '/settings'
    | '/system'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/cluster'
    | '/dashboard-settings'
    | '/items'
    | '/model-tracking'
    | '/secops'
    | '/serving'
    | '/settings'
    | '/system'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/cluster'
    | '/_layout/dashboard-settings'
    | '/_layout/items'
    | '/_layout/model-tracking'
    | '/_layout/secops'
    | '/_layout/serving'
    | '/_layout/settings'
    | '/_layout/system'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system': {
      id: '/_layout/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof LayoutSystemRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/serving': {
      id: '/_layout/serving'
      path: '/serving'
      fullPath: '/serving'
      preLoaderRoute: typeof LayoutServingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/secops': {
      id: '/_layout/secops'
      path: '/secops'
      fullPath: '/secops'
      preLoaderRoute: typeof LayoutSecopsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/model-tracking': {
      id: '/_layout/model-tracking'
      path: '/model-tracking'
      fullPath: '/model-tracking'
      preLoaderRoute: typeof LayoutModelTrackingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard-settings': {
      id: '/_layout/dashboard-settings'
      path: '/dashboard-settings'
      fullPath: '/dashboard-settings'
      preLoaderRoute: typeof LayoutDashboardSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cluster': {
      id: '/_layout/cluster'
      path: '/cluster'
      fullPath: '/cluster'
      preLoaderRoute: typeof LayoutClusterRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutClusterRoute: typeof LayoutClusterRoute
  LayoutDashboardSettingsRoute: typeof LayoutDashboardSettingsRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutModelTrackingRoute: typeof LayoutModelTrackingRoute
  LayoutSecopsRoute: typeof LayoutSecopsRoute
  LayoutServingRoute: typeof LayoutServingRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSystemRoute: typeof LayoutSystemRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutClusterRoute: LayoutClusterRoute,
  LayoutDashboardSettingsRoute: LayoutDashboardSettingsRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutModelTrackingRoute: LayoutModelTrackingRoute,
  LayoutSecopsRoute: LayoutSecopsRoute,
  LayoutServingRoute: LayoutServingRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSystemRoute: LayoutSystemRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
